### ISSUE TITLE
Error: Updating and loading repositories 

### ISSUE THREAD

**Issue by sanbroz** [Thinstation/thinstation-ng#1]
**while building on WSL2 as per instruction in readme I got the following error**

_Adding Package Dependencies

Adding 6.11.11-300.fc41.x86_64 module dependencies on other packages

Dependencies are clean!

Adding and install non-distributable binaries

Package ibus-libs has not yet been installed.
Would you like to try and install it now? Y/N:yUpdating and loading repositories:
 Fedora 41 - x86_64 - Updates                                                                                                            ???% |   0.0   B/s |   0.0   B |  00m00s
>>> Curl error (6): Could not resolve hostname for https://mirrors.fedoraproject.org/metalink?repo=updates-released-f41&arch=x86_64 [Could not resolve host: mirrors.fedoraprojec
>>> Curl error (6): Could not resolve hostname for https://mirrors.fedoraproject.org/metalink?repo=updates-released-f41&arch=x86_64 [Could not resolve host: mirrors.fedoraprojec
>>> Curl error (6): Could not resolve hostname for https://mirrors.fedoraproject.org/metalink?repo=updates-released-f41&arch=x86_64 [Could not resolve host: mirrors.fedoraprojec
>>> Curl error (6): Could not resolve hostname for https://mirrors.fedoraproject.org/metalink?repo=updates-released-f41&arch=x86_64 [Could not resolve host: mirrors.fedoraprojec
>>> Curl error (6): Could not resolve hostname for https://mirrors.fedoraproject.org/metalink?repo=updates-released-f41&arch=x86_64 [Could not resolve host: mirrors.fedoraprojec
>>> Curl error (6): Could not resolve hostname for https://mirrors.fedoraproject.org/metalink?repo=updates-released-f41&arch=x86_64 [Could not resolve host: mirrors.fedoraprojec
>>> Curl error (6): Could not resolve hostname for https://mirrors.fedoraproject.org/metalink?repo=updates-released-f41&arch=x86_64 [Could not resolve host: mirrors.fedoraprojec
>>> Curl error (6): Could not resolve hostname for https://mirrors.fedoraproject.org/metalink?repo=updates-released-f41&arch=x86_64 [Could not resolve host: mirrors.fedoraprojec
>>> Curl error (6): Could not resolve hostname for https://mirrors.fedoraproject.org/metalink?repo=updates-released-f41&arch=x86_64 [Could not resolve host: mirrors.fedoraprojec
>>> Curl error (6): Could not resolve hostname for https://mirrors.fedoraproject.org/metalink?repo=updates-released-f41&arch=x86_64 [Could not resolve host: mirrors.fedoraprojec
>>> Curl error (6): Could not resolve hostname for https://mirrors.fedoraproject.org/metalink?repo=updates-released-f41&arch=x86_64 [Could not resolve host: mirrors.fedoraprojec
>>> Curl error (6): Could not resolve hostname for https://mirrors.fedoraproject.org/metalink?repo=updates-released-f41&arch=x86_64 [Could not resolve host: mirrors.fedoraprojec
>>> Librepo error: Cannot prepare internal mirrorlist: Curl error (6): Could not resolve hostname for https://mirrors.fedoraproject.org/metalink?repo=updates-released-f41&arch=x
Error checking if metalink "https://mirrors.fedoraproject.org/metalink?repo=updates-released-f41&arch=x86_64" is in sync for repository "updates"
 Librepo error: Cannot prepare internal mirrorlist: Curl error (6): Could not resolve hostname for https://mirrors.fedoraproject.org/metalink?repo=updates-released-f41&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]_

**Comment by Doncuppjr** [comment]
WSL 1 or 2?

**Comment by sanbroz** [comment]
Its WSL2

**Comment by Doncuppjr** [comment]
ls -al /etc/resolv.conf
then ls -al whatever that points too

**Comment by sanbroz** [comment]
/etc/resolv.conf -> /mnt/wsl/resolv.conf

```
# This file was automatically generated by WSL. To stop automatic generation of this file, add the following entry to /etc/wsl.conf:
# [network]
# generateResolvConf = false
nameserver 172.29.208.1
```

https://superuser.com/questions/1533291/how-do-i-change-the-dns-settings-for-wsl2

still same issue

**Comment by Doncuppjr** [comment]
Interesting. Can you ping the DNS? Do you have an IP? A route?

**Comment by Doncuppjr** [comment]
Possibly this was a branch problem. I had the default branch still set to main, instead of 7.0-Stable. 7.0-Stable is where I made the accommodations for WSL.

**Comment by sanbroz** [comment]
yes using
`git clone --branch 7.0-Stable https://github.com/Thinstation/thinstation-ng.git `
solved the issue
